name: Publish Node.js Package

on:
  push:
    branches:
      - main

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: set git config
        run: |
          git config user.name "github-action"
          git config user.email "action@github.com"
      - name: Install & build
        run: |
          yarn install --frozen-lockfile
          npm version patch
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version package.json -r"
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
      - name: Commit and push
        run: |
          git commit -am "update - ${{ steps.version.outputs.value }}"
          git push
      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
