name: Publish Node.js Package

on:
  push:
    branches:
      - main

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 16
      #     registry-url: https://npm.pkg.github.com/
      # - name: Install & build
      #   run: |
      #     cd node
      #     yarn install --frozen-lockfile
      #     yarn build
      #     npm version patch
      - run: npm version patch
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version package.json -r"
      - name: Push updated version
        run: |
          git config user.name github-action
          git config user.email action@github.com
          git commit -am "update - ${{ steps.version.outputs.value }}"
          git push
        # - name: Publish
        #   run: |
        #     cd node
        #     npm publish
        # env:
        #   NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
